In [1]:
from scipy import signal
import numpy as np
import matplotlib.pyplot as plt
import japanize_matplotlib

## signal.lfilterの使い方

In [89]:
x = np.linspace(start=1, stop=20, num=20)
x

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20.])

In [94]:
a = np.array([1])
b = np.array([2,3])

In [95]:
signal.lfilter(a=a, b=b, x=x)

array([ 2.,  7., 12., 17., 22., 27., 32., 37., 42., 47., 52., 57., 62.,
       67., 72., 77., 82., 87., 92., 97.])

## sm.tsa.arma_generate_sampleの使い方

In [13]:
arparams = np.array([.75, -.25])
maparams = np.array([.65, .35])
arparams, maparams

(array([ 0.75, -0.25]), array([0.65, 0.35]))

In [14]:
ar = np.r_[1, -arparams] # add zero-lag and negate
ma = np.r_[1, maparams] # add zero-lag
ar, ma

(array([ 1.  , -0.75,  0.25]), array([1.  , 0.65, 0.35]))

In [17]:
import statsmodels.api as sm
y = sm.tsa.arma_generate_sample(ar, ma, 20)
y

array([-1.08755305, -1.48265353, -1.37709986, -1.16313735, -2.44480687,
       -2.95479431, -3.05474881, -2.05246351, -1.10385085, -2.02954189,
       -1.14412207, -0.93572629, -1.75489813, -1.42194658, -0.15110292,
       -1.70806492, -3.89438952, -5.12792596, -4.35884522, -2.20525464])

In [69]:
def func(size):
    if type(size) is not int:
        size = size[0]
    return np.linspace(start=1, stop=size, num=size)

In [73]:
func(size=4)

array([1., 2., 3., 4.])

In [64]:
np.random.standard_normal(size=[2,3])

array([[ 1.39725194, -0.0017224 , -1.22798038],
       [ 0.66982351,  0.77893188,  1.06277484]])

In [88]:
sm.tsa.arma_generate_sample(ar=np.array([1.]), ma=np.array([1]), nsample=20, distrvs=func, burnin=5)

array([ 6.,  7.,  8.,  9., 10., 11., 12., 13., 14., 15., 16., 17., 18.,
       19., 20., 21., 22., 23., 24., 25.])

In [82]:
np.random.seed(seed = 1)
sm.tsa.arma_generate_sample(ar=np.array([1.]), ma=np.array([1]), nsample=10)

array([ 1.62434536, -0.61175641, -0.52817175, -1.07296862,  0.86540763,
       -2.3015387 ,  1.74481176, -0.7612069 ,  0.3190391 , -0.24937038])

In [83]:
np.random.seed(seed = 1)
np.random.standard_normal(size=10)

array([ 1.62434536, -0.61175641, -0.52817175, -1.07296862,  0.86540763,
       -2.3015387 ,  1.74481176, -0.7612069 ,  0.3190391 , -0.24937038])